add_compile_definitions(NUCLEAR_BACKEND_SDL3)

if (PLATFORM_WEB)
    set(SDLTTF_VENDORED ON CACHE BOOL "" FORCE)
    set(SDLTTF_HARFBUZZ OFF CACHE BOOL "" FORCE)
    set(SDLTTF_PLUTOSVG OFF CACHE BOOL "" FORCE)
    set(SDLTTF_INSTALL OFF CACHE BOOL "" FORCE)

    add_link_options(-sMIN_WEBGL_VERSION=2 -sMAX_WEBGL_VERSION=2 -sALLOW_MEMORY_GROWTH=1 -sINITIAL_MEMORY=2gb -sMAXIMUM_MEMORY=4096Mb -sSTACK_SIZE=1048576 -sOFFSCREENCANVAS_SUPPORT=1 -sFORCE_FILESYSTEM=1 -sEXIT_RUNTIME=1 -sASYNCIFY -lidbfs.js)
endif()

if(PLATFORM_IOS)
    set(SDL_SHARED OFF CACHE BOOL "" FORCE)
    set(SDL_STATIC ON CACHE BOOL "" FORCE)
endif()

find_package(SDL3 QUIET)
if (NOT SDL3_FOUND)
    message(STATUS "Getting SDL3 from Github")
    include_dependency(SDL3 https://github.com/libsdl-org/SDL.git release-3.4.8)
else()
    message(STATUS "Using local SDL3")
endif()

set(SDLIMAGE_VENDORED ON)
set(SDLIMAGE_AVIF OFF)
set(SDLIMAGE_BMP OFF)
set(SDLIMAGE_JPEG OFF)
set(SDLIMAGE_WEBP OFF)
set(SDLIMAGE_TIF OFF)
set(PNG_ARM_NEON "off" CACHE STRING "" FORCE)

find_package(SDL3_image QUIET)
if (NOT SDL3_image_FOUND)
    message(STATUS "Getting SDL3_image from Github")
    include_dependency(SDL3_image https://github.com/libsdl-org/SDL_image.git release-3.4.4)
else()
    message(STATUS "Using local SDL3_image")
endif()

if(NOT PLATFORM_WEB)
    set(SDLTTF_VENDORED ON)
    find_package(SDL3_ttf QUIET)
    if (NOT SDL3_ttf_FOUND)
        message(STATUS "Getting SDL3_ttf from Github")
        include_dependency(SDL3_ttf https://github.com/libsdl-org/SDL_ttf.git release-3.2.2)
    else()
        message(STATUS "Using local SDL3_ttf")
    endif()
else()
    include_dependency(SDL3_ttf https://github.com/libsdl-org/SDL_ttf.git release-3.2.2)
endif()

if(PLATFORM_WINDOWS OR PLATFORM_LINUX)
    message(STATUS "Getting GLEW from Github")
    set(glew-cmake_BUILD_SHARED OFF CACHE BOOL "" FORCE)
    set(glew-cmake_BUILD_STATIC ON CACHE BOOL "" FORCE)
    set(ONLY_LIBS ON CACHE BOOL "" FORCE)
    include_dependency(glew https://github.com/Perlmint/glew-cmake.git glew-cmake-2.2.0-1)
endif()

if(PLATFORM_IOS)
    find_library(OPENGLES_FRAMEWORK OpenGLES)
else()
    find_package(OpenGL REQUIRED)
endif()
