# Setup defines
if(WIN32)
    add_compile_definitions(PLATFORM_WINDOWS)
    set(PLATFORM_WINDOWS ON)
elseif(APPLE AND NOT EMSCRIPTEN AND NOT IOS)
    add_compile_definitions(PLATFORM_MACOS)
    set(PLATFORM_MACOS ON)
elseif(UNIX AND NOT APPLE AND NOT EMSCRIPTEN)
    add_compile_definitions(PLATFORM_LINUX)
    set(PLATFORM_LINUX ON)
elseif(EMSCRIPTEN)
    add_compile_definitions(PLATFORM_WEB)
    set(PLATFORM_WEB ON)
elseif (IOS)
    add_compile_definitions(PLATFORM_IOS)
    set(PLATFORM_IOS ON)
endif()

if(MSVC)
    add_compile_options(/bigobj /wd4102)
elseif(PLATFORM_MACOS OR PLATFORM_IOS)
    enable_language(OBJC)
    enable_language(OBJCXX)
else()
    add_compile_options(-Wno-unused-label)
endif()

if (PLATFORM_IOS)
    set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
endif()